framework:
    secret: '%env(APP_SECRET)%'
    #default_locale: en
    #csrf_protection: ~
    #http_method_override: true

    # uncomment this entire section to enable sessions
    session:
       handler_id: ~

    #esi: ~
    #fragments: ~
    assets:
        json_manifest_path: '%kernel.project_dir%/public/build/manifest.json'
    php_errors:
        log: true

    serializer:
        enabled: true